"""Fail-closed correctness gate for the unified runner.

Unlike a smoke test that only checks "output happens", this runs a real
per-modality **correctness** check on every registered model and FAILS if any
model doesn't produce the expected result:

- language : known-answer (capital of France -> "Paris")
- vlm      : vision grounding (a red image -> "red")
- ocr      : rendered text -> contains the text
- asr      : transcribe real speech -> matches the spoken words
- tts      : synth -> Whisper transcribes it back -> matches the input
- vad      : real speech -> at least one speech segment
- audio_cls: real speech -> top label is "Speech"
- embeddings: paraphrase pair more similar than an unrelated pair
- cad      : spec -> emitted CadQuery executes to the expected bounding box

The speech fixture is generated by the real Kokoro TTS, so ASR/VAD/audio-cls are
checked against genuine speech with known content.
"""

from __future__ import annotations

import contextlib
import io
import tempfile
from dataclasses import dataclass

# Spoken sentence used for the TTS->ASR round-trip and the ASR fixture.
_SPEECH_TEXT = "The quick brown fox jumps over the lazy dog"
_SPEECH_WORDS = {"quick", "brown", "fox", "jumps", "lazy", "dog"}


@dataclass
class CheckResult:
    model: str
    modality: str
    ok: bool
    detail: str


def _norm(s: str) -> str:
    return "".join(c.lower() for c in (s or "") if c.isalnum() or c.isspace())


def _render_text_image(path: str, lines: list[str]) -> str:
    from PIL import Image, ImageDraw, ImageFont

    img = Image.new("RGB", (520, 60 + 56 * len(lines)), "white")
    d = ImageDraw.Draw(img)
    try:
        font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial.ttf", 40)
    except Exception:
        font = ImageFont.load_default()
    for i, line in enumerate(lines):
        d.text((20, 20 + 56 * i), line, fill="black", font=font)
    img.save(path)
    return path


def _solid_image(path: str, color: str) -> str:
    from PIL import Image

    Image.new("RGB", (224, 224), color).save(path)
    return path


def _write_wav(path: str, waveform, sr: int) -> str:
    import numpy as np
    import soundfile as sf

    sf.write(path, np.asarray(waveform, dtype=np.float32).reshape(-1), int(sr))
    return path


def _run_raw(entry, **inputs):
    """Call an adapter directly and return its raw RunOutput (not serialized)."""
    from . import runner

    loaded = runner.load_cached(entry.key)
    kw = {"text": None, "image": None, "audio": None, "document": None}
    kw.update(inputs)
    return entry.runner(loaded, **kw)


def _build_fixtures(tmp: str) -> dict:
    """Create the shared inputs: a red image, a document image, a speech clip."""
    fx = {
        "red": _solid_image(f"{tmp}/red.png", "red"),
        "green": _solid_image(f"{tmp}/green.png", "green"),
        "doc": _render_text_image(f"{tmp}/doc.png", ["Invoice 12345", "Total: $42.00"]),
    }
    # Real speech via Kokoro TTS, so ASR/VAD/audio-cls run on genuine speech.
    from . import runner

    out = _run_raw(runner.REGISTRY["kokoro"], text=_SPEECH_TEXT)
    waveform, sr = out.audio
    fx["speech"] = _write_wav(f"{tmp}/speech.wav", waveform, sr)
    return fx


# --------------------------------------------------------------------------- #
# Per-modality correctness checks. Each returns (ok, detail).                 #
# --------------------------------------------------------------------------- #


def _check_language(entry, fx) -> tuple[bool, str]:
    out = _run_raw(entry, text="What is the capital of France? Answer in one word.")
    ok = "paris" in (out.text or "").lower()
    return ok, (out.text or "")[:60]


def _check_vlm(entry, fx) -> tuple[bool, str]:
    # Require real color discrimination: red image -> "red" (not "green"), and
    # green image -> "green". A model that answers the same regardless of the
    # image (e.g. a degenerate quant) fails.
    q = "What color is this image? Answer with one word."
    r = (_run_raw(entry, text=q, image=fx["red"]).text or "").lower()
    g = (_run_raw(entry, text=q, image=fx["green"]).text or "").lower()
    ok = ("red" in r and "green" not in r) and ("green" in g)
    return ok, f"red->{r.strip()[:12]!r} green->{g.strip()[:12]!r}"


def _check_ocr(entry, fx) -> tuple[bool, str]:
    out = _run_raw(entry, document=fx["doc"])
    ok = "12345" in (out.text or "")
    return ok, (out.text or "")[:60]


def _check_asr(entry, fx) -> tuple[bool, str]:
    out = _run_raw(entry, audio=fx["speech"])
    words = set(_norm(out.text).split())
    hit = len(_SPEECH_WORDS & words)
    return hit >= 3, f"{hit}/6 keywords: {(out.text or '')[:50]}"


def _check_tts(entry, fx) -> tuple[bool, str]:
    out = _run_raw(entry, text=_SPEECH_TEXT)
    waveform, sr = out.audio
    with tempfile.TemporaryDirectory() as td:
        wav = _write_wav(f"{td}/tts.wav", waveform, sr)
        import mlx_whisper

        with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
            r = mlx_whisper.transcribe(wav, path_or_hf_repo="mlx-community/whisper-tiny")
    words = set(_norm(r.get("text") or "").split())
    hit = len(_SPEECH_WORDS & words)
    return hit >= 3, f"round-trip {hit}/6: {(r.get('text') or '')[:45]}"


def _check_vad(entry, fx) -> tuple[bool, str]:
    out = _run_raw(entry, audio=fx["speech"])
    segs = out.data or []
    return len(segs) >= 1, f"{len(segs)} speech segment(s)"


def _check_audio_cls(entry, fx) -> tuple[bool, str]:
    out = _run_raw(entry, audio=fx["speech"])
    labels = [d.get("label", "").lower() for d in (out.data or [])]
    ok = any("speech" in lbl for lbl in labels[:3])
    return ok, f"top: {labels[:3]}"


def _check_embeddings(entry, fx) -> tuple[bool, str]:
    import numpy as np

    out = _run_raw(
        entry, text=["a cat sleeps on the mat", "a kitten naps on the rug", "stocks fell"]
    )
    v = np.asarray(out.data)
    cos = lambda a, b: float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b) + 1e-9))
    para, unrel = cos(v[0], v[1]), cos(v[0], v[2])
    return para > unrel + 0.1, f"paraphrase {para:.2f} > unrelated {unrel:.2f}"


def _check_cad(entry, fx) -> tuple[bool, str]:
    out = _run_raw(entry, text="a cylinder with radius 5mm and height 10mm")
    bbox = out.data.get("summary", "")
    ok = "(10.0, 10.0, 10.0)" in bbox
    return ok, bbox[:60]


_CHECKS = {
    "language": _check_language,
    "vlm": _check_vlm,
    "ocr": _check_ocr,
    "asr": _check_asr,
    "tts": _check_tts,
    "vad": _check_vad,
    "audio_cls": _check_audio_cls,
    "embeddings": _check_embeddings,
    "cad": _check_cad,
}


def verify(model_ids: list[str] | None = None) -> tuple[list[CheckResult], bool]:
    """Run the correctness gate. Returns (results, all_ok)."""
    from . import runner

    runner._ensure_registry()
    entries = runner.list_entries()
    if model_ids:
        wanted = {m.lower() for m in model_ids}
        entries = [e for e in entries if e.key in wanted]

    results: list[CheckResult] = []
    with tempfile.TemporaryDirectory() as tmp:
        fx = _build_fixtures(tmp)
        for entry in entries:
            check = _CHECKS.get(entry.modality)
            if check is None:
                results.append(
                    CheckResult(entry.key, entry.modality, False, "no correctness check")
                )
                continue
            try:
                with (
                    contextlib.redirect_stdout(io.StringIO()),
                    contextlib.redirect_stderr(io.StringIO()),
                ):
                    ok, detail = check(entry, fx)
                results.append(CheckResult(entry.key, entry.modality, ok, detail))
            except Exception as e:  # a crash is a correctness failure
                results.append(
                    CheckResult(entry.key, entry.modality, False, f"{type(e).__name__}: {e}")
                )
    all_ok = all(r.ok for r in results)
    return results, all_ok
